title: dan jacobson
description: machine learning engineer
baseurl: ""
url: https:danjacobson.net 

# site settings
taglong: Dan Jacobson's personal website
tagshort: Dan's website

# author settings
author:
  name: Dan Jacobson
  email: danrowejacobson@gmail.com
photo: assets/files/photo.jpg

# profile links
profile:
  mail: mailto:danrowejacobson@gmail.com
  github: https://github.com/dan-jacobson
  linkedin: https://www.linkedin.com/in/daniel-rowe-jacobson
  # goodreads: https://www.goodreads.com/user/show/46060439-dan-jacobson

# build settings
permalink: pretty
exclude:
  - cvless.gemspec
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - docker-compose.yml
  - _posts_archive

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
